### ISSUE TITLE
Eclipse Classpath

### ISSUE THREAD

**Issue by rsun0** [joemahmah/2022-frc-2015#12]
Some people have a problem where Eclipse cannot resolve classpaths for networktables and wpilib. Others do not have the problem. We should figure out what is causing the problem and make it work for everybody.

**Comment by joemahmah** [comment]
Added a wiki page on this: https://github.com/joemahmah/2022-frc-2015/wiki/Fixing-Project-Import-Errors

**Comment by nusgart** [comment]
The .classpath changes I have commited might fix this

**Comment by rsun0** [comment]
Issue resolved. If you are still having problems, ask me.
