### ISSUE TITLE
Pneumatics Fix

### ISSUE THREAD

**Issue by joemahmah** [joemahmah/2022-frc-2015#17]
The subsystem and command need to also include another piston that opens and closes the "claw" attached to the fork lift.

**Comment by GrantFinnegan** [comment]
We are doing the claw? I thought we decided against that? I can definitely get the subsystem operational. Should we make all pneumatics under the pneumatics subsystem, would we want a seperate class for the claw pneumatics, or shoulw we just create two pneumatics objects from the pneumatic class

**Comment by Vjedi729** [comment]
This has already been resolved. I am checking the Robot Map.

**Comment by joemahmah** [comment]
Please don't close until branch has been merged into master.
