### ISSUE TITLE
Lidar wrapper

### ISSUE THREAD

**Issue by GrantFinnegan** [joemahmah/2022-frc-2015#20]
Create a wrapper for a light sensor. Methods should be able to get sensor data and make them into something the program can read and use (i.e. a double value).

**Comment by esloan** [comment]
Can you provide descriptions for these so other people can help? There's no point in making the issue without describing it.

**Comment by GrantFinnegan** [comment]
I would if the issues were ones that took any considerable amount of time. These ones were quick and small issues

**Comment by joemahmah** [comment]
Only close when branch is merged into master. Also descriptions are needed no matter how small or quick an issue may be.
