### ISSUE TITLE
Tank Drive Subsystem

### ISSUE THREAD

**Issue by joemahmah** [joemahmah/2022-frc-2015#4]
Write a simple subsystem for the tank drive. The subsystem's functions (i.e. forward(), reverse(), etc...) will get port numbers via RobotMap. Tank drives need to have motors on each side spinning in sync.

Motors x4

**Comment by nusgart** [comment]
I have the code for this written but have not pushed it yet as I already have code written for other issues- should I anyways?
EDIT: I have created a new tank branch and merged only relevant commits and will push it to the remote.
EDIT 2: I have pushed the tank branch
