### ISSUE TITLE
Fork Lift Subsystem

### ISSUE THREAD

**Issue by joemahmah** [joemahmah/2022-frc-2015#7]
Write a simple subsystem for the fork lift. The subsystem's functions (i.e. up(), down(), etc...) will get port numbers via RobotMap. The subsystem will also handle sensors (the limit switches).

Sensors:
Limit Switch x2

Motors x1

**Comment by GrantFinnegan** [comment]
could I work on this? If so, do we want the speed of the winch to be binary, or variable?

**Comment by joemahmah** [comment]
Feel free to work on it. The speed should be variable.

**Comment by joemahmah** [comment]
Just remember to make a new branch.
